### ISSUE TITLE
PMS5003 ReadTimout

### ISSUE THREAD

**Issue by lm93547** [pimoroni/pms5003-python#10]
I have what appears to be the common issue. I am running the latest Raspbian OS desktop. I have installed the enviro + software and the examples mostly run fine until the dreaded:

`  File "/usr/local/lib/python3.6/dist-packages/pms5003/__init__.py", line 121, in read
    raise ReadTimeoutError("PMS5003 Read Timeout")
pms5003.ReadTimeoutError: PMS5003 Read Timeout`

I have added: `dtoverlay=pi3-miniuart-bt` to my `/boot/config.txt`

Any ideas on why this would be happening? I can hear the sensor turning on so it does not seem to be a hardware issue.. I have tried re-seating the cable, using a different cable, but nothing works. Any help much appreciated.

**Comment by kevinjwalters** [comment]
When does it happen? I've been using a different setup, a PMS5003 attached to an Enviro+ FeatherWing with a Feather nRF52840 Express.

The PMS5003 needs 5V to work so worth verifying that level is correct. I've also seen it take a fraction over 9 seconds to respond on the odd occasion which would be beyond the read timeout in this library if you try and read a value _immediately_ after creating the `PMS5003` object.

**Comment by SamStudio8** [comment]
Old thread but this happened to me today, I found I had to change the example to use `/dev/ttys0` (serial0) rather than `/dev/ttyAMA0` (serial1).
