### ISSUE TITLE
ReadTimeoutError in Example code 

### ISSUE THREAD

**Issue by alexanderfrey** [pimoroni/pms5003-python#4]
Hi,

I just received my second pms5003 sensor and still can't get any reading from the device. From my understanding both the ARM I2C interface needs to be enabled and the serial port hardware. In addition to that the /etc/boot.txt does list a line dtoverlay=pi3-miniuart-bt

Also I ran the install script several times on a raspberry pi 4. 

This code does also not do anything:

```
import serial

bus = serial.Serial('/dev/ttyAMA0', baudrate=9600, timeout=4)
bus.flushInput()
while True:
    value = bus.read(4)
    if len(value) > 0:
        print(value)
```

What am I doing wrong. Can I run some checks on interfaces or do you have another idea ?

Thanks for your help,
Alexander

**Comment by cipy** [comment]
Hi,

Have you done first?

$ sudo apt update && sudo apt upgrade

Then clone pimoroni’s GitHub Repo for environ+ and run its install script? I think you need to run it with sudo too.


Best,
Ciprian

**Comment by alexanderfrey** [comment]
Thanks. Did all that in that very order. I just detached my lcd screen that also added a dtoverlay parameter to the boot.txt   But that also did not help.

**Comment by alexanderfrey** [comment]
By the way: I run the pms5003 through the Enviro+ extension board if that shouldn't be clear. Thanks for your help

The script that does not do anything is particulates.py btw. The other scripts (weather.py etc...) do work

**Comment by Gadgetoid** [comment]
Double-check you have `dtoverlay=pi3-miniuart-bt` (which might be the dtoverlay you refer to) in your `/boot/config.txt` and also try re-seating the cable between the PMS5003 and board, since this is often caused by a flaky connection.

**Comment by Gadgetoid** [comment]
Did you ever get to the bottom of this?
