### ISSUE TITLE
ERROR MESSAGE 

### ISSUE THREAD

**Issue by davidchen753** [pimoroni/pms5003-python#8]
ERROR MESSAGE IS AS BELOW.
sometimes OK, but sometimes FAIL.
sometimes OK at first, then FAIL.
WHAT WRONG?
Is it hardware problems?

============================================

pi@raspberrypi:~/pms5003-python/examples $ sudo python specific.py
specific.py - Continously print a specific data value.

Press Ctrl+C to exit!

Traceback (most recent call last):
  File "specific.py", line 17, in <module>
    timeout=2
TypeError: __init__() got an unexpected keyword argument 'timeout'

**Comment by Gadgetoid** [comment]
`specific.py` does not attempt to pass a `timeout` argument to PMS5003, so I don't know why you're seeing this error- https://github.com/pimoroni/pms5003-python/blob/master/examples/specific.py

Could you post the code that you are running?
